from langchain.chains import RetrievalQA
from langchain.prompts import PromptTemplate
from langchain.chains import RetrievalQA
from langchain.chains import create_retrieval_chain
from langchain.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate
from langchain_groq.chat_models import ChatGroq
from langchain.prompts.chat import ChatPromptTemplate
from langchain.chains import LLMChain
from langchain_groq.chat_models import ChatGroq
from langchain_pinecone import PineconeVectorStore